// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: car-display

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_battery_level_arc = NULL;
lv_obj_t * ui_battery_text_label = NULL;
lv_obj_t * ui_battery_percentage = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0C161E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery_level_arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_battery_level_arc, 210);
    lv_obj_set_height(ui_battery_level_arc, 210);
    lv_obj_set_align(ui_battery_level_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery_level_arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_battery_level_arc, 0);
    lv_arc_set_bg_angles(ui_battery_level_arc, 0, 360);
    lv_arc_set_rotation(ui_battery_level_arc, 270);
    lv_obj_set_style_arc_color(ui_battery_level_arc, lv_color_hex(0x1E3949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_battery_level_arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_battery_level_arc, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_battery_level_arc, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_battery_level_arc, &ui_img_asset_2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_battery_level_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery_level_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_battery_text_label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_battery_text_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery_text_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battery_text_label, 0);
    lv_obj_set_y(ui_battery_text_label, 30);
    lv_obj_set_align(ui_battery_text_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battery_text_label, "Battery");
    lv_obj_set_style_text_color(ui_battery_text_label, lv_color_hex(0x3A444C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_battery_text_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_battery_text_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery_percentage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_battery_percentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery_percentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battery_percentage, 0);
    lv_obj_set_y(ui_battery_percentage, -5);
    lv_obj_set_align(ui_battery_percentage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battery_percentage, "---");
    lv_obj_set_style_text_font(ui_battery_percentage, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_battery_level_arc = NULL;
    ui_battery_text_label = NULL;
    ui_battery_percentage = NULL;

}
